# Generated by Django 5.1.4 on 2024-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creaturesApp', '0003_ticket_delete_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ref_link',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
